# Generated by Django 5.2.6 on 2025-09-15 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id_hotel', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=100)),
                ('calificacion', models.FloatField()),
                ('estado', models.BooleanField()),
                ('fecha_creacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LugarTuristico',
            fields=[
                ('id_lugar', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo_pago', models.CharField(max_length=50)),
                ('monto', models.FloatField()),
                ('fecha', models.DateField()),
                ('fecha_creacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ci', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('contrasenia', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('pasaporte', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
                ('fecha_creacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('caracteristicas', models.TextField()),
                ('precio', models.FloatField()),
                ('disponible', models.BooleanField()),
                ('fecha_creacion', models.DateField()),
                ('cant_huespedes', models.IntegerField()),
                ('codigo_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField()),
                ('fecha_caducidad', models.DateField()),
                ('fecha_creacion', models.DateField()),
                ('codigo_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotel')),
                ('id_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pago')),
                ('num_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.habitacion')),
                ('ci_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id_paquete', models.BigIntegerField(primary_key=True, serialize=False)),
                ('precio', models.FloatField()),
                ('fecha_creacion', models.DateField()),
                ('id_lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lugarturistico')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Sugerencias',
            fields=[
                ('id_sugerencia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('preferencias', models.TextField()),
                ('fecha_creacion', models.DateField()),
                ('ci_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
    ]