# Etapa 1: Construcción
FROM node:20-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build --configuration=production

# Etapa 2: Servidor Nginx
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf

# --- CORRECCIÓN AQUÍ ---
# Cambiamos 'frontend' por 'frontend-turismo-hoteleria'
COPY --from=build /app/dist/frontend-turismo-hoteleria/browser /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]