services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      # Local model cache folder (not committed). Cross-platform relative path.
      - ./.ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    environment:
      OLLAMA_BASE_URL: "http://ollama:11434"
    depends_on:
      ollama:
        condition: service_started
