# Generated by Django 5.0.6 on 2025-10-13 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id_hotel', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=100)),
                ('calificacion', models.FloatField()),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('url', models.CharField(default='', max_length=255)),
                ('url_imagen_hotel', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LugarTuristico',
            fields=[
                ('id_lugar', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('horario', models.CharField(blank=True, default='', max_length=255)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('url_image_lugar_turistico', models.TextField(blank=True, default='')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_pago', models.CharField(max_length=50)),
                ('monto', models.FloatField()),
                ('fecha', models.DateField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=255, unique=True)),
                ('contrasenia', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('superadmin', 'Superadmin'), ('usuario', 'Usuario')], max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('pasaporte', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('num', models.BigAutoField(primary_key=True, serialize=False)),
                ('caracteristicas', models.TextField()),
                ('precio', models.FloatField()),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('cant_huespedes', models.IntegerField()),
                ('codigo_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id_paquete', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='sin nombre', max_length=255)),
                ('tipo', models.CharField(blank=True, default='', max_length=100)),
                ('precio', models.FloatField()),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('id_hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
                ('id_lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lugarturistico')),
            ],
        ),
        migrations.CreateModel(
            name='Sugerencias',
            fields=[
                ('id_sugerencia', models.BigAutoField(primary_key=True, serialize=False)),
                ('preferencias', models.TextField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField()),
                ('fecha_caducidad', models.DateField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('codigo_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
                ('id_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pago')),
                ('id_paquete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paquete')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('num_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.habitacion')),
            ],
            options={
                'indexes': [models.Index(fields=['num_habitacion', 'fecha_reserva', 'fecha_caducidad'], name='core_reserv_num_hab_87059e_idx')],
            },
        ),
    ]
